//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoorNavigation.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("IndoorNavigation.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string HOME_STRING {
            get {
                return ResourceManager.GetString("HOME_STRING", resourceCulture);
            }
        }
        
        internal static string LOCATION_STRING {
            get {
                return ResourceManager.GetString("LOCATION_STRING", resourceCulture);
            }
        }
        
        internal static string SELECT_LOCATION_STRING {
            get {
                return ResourceManager.GetString("SELECT_LOCATION_STRING", resourceCulture);
            }
        }
        
        internal static string EDIT_STRING {
            get {
                return ResourceManager.GetString("EDIT_STRING", resourceCulture);
            }
        }
        
        internal static string SETTING_STRING {
            get {
                return ResourceManager.GetString("SETTING_STRING", resourceCulture);
            }
        }
        
        internal static string BEDITECH_STRING {
            get {
                return ResourceManager.GetString("BEDITECH_STRING", resourceCulture);
            }
        }
        
        internal static string DOWNLOAD_QRCODE_MAP_STRING {
            get {
                return ResourceManager.GetString("DOWNLOAD_QRCODE_MAP_STRING", resourceCulture);
            }
        }
        
        internal static string DOWNLOAD_MAP_STRING {
            get {
                return ResourceManager.GetString("DOWNLOAD_MAP_STRING", resourceCulture);
            }
        }
        
        internal static string DELETE_MAP_STRING {
            get {
                return ResourceManager.GetString("DELETE_MAP_STRING", resourceCulture);
            }
        }
        
        internal static string VOICE_TEST_STRING {
            get {
                return ResourceManager.GetString("VOICE_TEST_STRING", resourceCulture);
            }
        }
        
        internal static string CHANGE_LANGUAGE_STRING {
            get {
                return ResourceManager.GetString("CHANGE_LANGUAGE_STRING", resourceCulture);
            }
        }
        
        internal static string SELECT_LANGUAGE_STRING {
            get {
                return ResourceManager.GetString("SELECT_LANGUAGE_STRING", resourceCulture);
            }
        }
        
        internal static string CHINESE_STRING {
            get {
                return ResourceManager.GetString("CHINESE_STRING", resourceCulture);
            }
        }
        
        internal static string ENGLISH_STRING {
            get {
                return ResourceManager.GetString("ENGLISH_STRING", resourceCulture);
            }
        }
        
        internal static string LICENSE_AND_PRIVACY_STRING {
            get {
                return ResourceManager.GetString("LICENSE_AND_PRIVACY_STRING", resourceCulture);
            }
        }
        
        internal static string LICENSE_STRING {
            get {
                return ResourceManager.GetString("LICENSE_STRING", resourceCulture);
            }
        }
        
        internal static string PRIVACY_STRING {
            get {
                return ResourceManager.GetString("PRIVACY_STRING", resourceCulture);
            }
        }
        
        internal static string OTHERS_STRING {
            get {
                return ResourceManager.GetString("OTHERS_STRING", resourceCulture);
            }
        }
        
        internal static string FEEDBACK_STRING {
            get {
                return ResourceManager.GetString("FEEDBACK_STRING", resourceCulture);
            }
        }
        
        internal static string ABOUT_BEDI_STRING {
            get {
                return ResourceManager.GetString("ABOUT_BEDI_STRING", resourceCulture);
            }
        }
        
        internal static string PREFERENCES_STRING {
            get {
                return ResourceManager.GetString("PREFERENCES_STRING", resourceCulture);
            }
        }
        
        internal static string VOICE_SPEAK_STRING {
            get {
                return ResourceManager.GetString("VOICE_SPEAK_STRING", resourceCulture);
            }
        }
        
        internal static string VOICE_SELECT_STRING {
            get {
                return ResourceManager.GetString("VOICE_SELECT_STRING", resourceCulture);
            }
        }
        
        internal static string VOICE_SETTING_STRING {
            get {
                return ResourceManager.GetString("VOICE_SETTING_STRING", resourceCulture);
            }
        }
        
        internal static string PLAY_VOICE_TEST_STRING {
            get {
                return ResourceManager.GetString("PLAY_VOICE_TEST_STRING", resourceCulture);
            }
        }
        
        internal static string CULTURE_VERSION_STRING {
            get {
                return ResourceManager.GetString("CULTURE_VERSION_STRING", resourceCulture);
            }
        }
        
        internal static string OK_STRING {
            get {
                return ResourceManager.GetString("OK_STRING", resourceCulture);
            }
        }
        
        internal static string CANCEL_STRING {
            get {
                return ResourceManager.GetString("CANCEL_STRING", resourceCulture);
            }
        }
        
        internal static string GO_NAVIGATION_HOME_PAGE_STRING {
            get {
                return ResourceManager.GetString("GO_NAVIGATION_HOME_PAGE_STRING", resourceCulture);
            }
        }
        
        internal static string GO_SETTING_PAGE_STRING {
            get {
                return ResourceManager.GetString("GO_SETTING_PAGE_STRING", resourceCulture);
            }
        }
        
        internal static string DOWNLOAD_NAVIGATION_GRAPH_STRING {
            get {
                return ResourceManager.GetString("DOWNLOAD_NAVIGATION_GRAPH_STRING", resourceCulture);
            }
        }
        
        internal static string FLASH_STRING {
            get {
                return ResourceManager.GetString("FLASH_STRING", resourceCulture);
            }
        }
        
        internal static string CHOOSE_MAP_STRING {
            get {
                return ResourceManager.GetString("CHOOSE_MAP_STRING", resourceCulture);
            }
        }
        
        internal static string ALL_STRING {
            get {
                return ResourceManager.GetString("ALL_STRING", resourceCulture);
            }
        }
        
        internal static string WARN_STRING {
            get {
                return ResourceManager.GetString("WARN_STRING", resourceCulture);
            }
        }
        
        internal static string ASK_IF_CANCEL_ALL_MAP_STRING {
            get {
                return ResourceManager.GetString("ASK_IF_CANCEL_ALL_MAP_STRING", resourceCulture);
            }
        }
        
        internal static string ASK_IF_CANCEL_MAP_STRING {
            get {
                return ResourceManager.GetString("ASK_IF_CANCEL_MAP_STRING", resourceCulture);
            }
        }
        
        internal static string MESSAGE_STRING {
            get {
                return ResourceManager.GetString("MESSAGE_STRING", resourceCulture);
            }
        }
        
        internal static string SUCCESSFULLY_DELETE_STRING {
            get {
                return ResourceManager.GetString("SUCCESSFULLY_DELETE_STRING", resourceCulture);
            }
        }
        
        internal static string MAP_STRING {
            get {
                return ResourceManager.GetString("MAP_STRING", resourceCulture);
            }
        }
        
        internal static string ERROR_STRING {
            get {
                return ResourceManager.GetString("ERROR_STRING", resourceCulture);
            }
        }
        
        internal static string ERROR_TO_DELETE_STRING {
            get {
                return ResourceManager.GetString("ERROR_TO_DELETE_STRING", resourceCulture);
            }
        }
        
        internal static string SUCCESSFULLY_DOWNLOAD_MAP_STRING {
            get {
                return ResourceManager.GetString("SUCCESSFULLY_DOWNLOAD_MAP_STRING", resourceCulture);
            }
        }
        
        internal static string FAILED_DOWNLOAD_MAP_STRING {
            get {
                return ResourceManager.GetString("FAILED_DOWNLOAD_MAP_STRING", resourceCulture);
            }
        }
        
        internal static string NOTIFY_STRING {
            get {
                return ResourceManager.GetString("NOTIFY_STRING", resourceCulture);
            }
        }
        
        internal static string SURE_TO_OPEN_WEBSITE_STRING {
            get {
                return ResourceManager.GetString("SURE_TO_OPEN_WEBSITE_STRING", resourceCulture);
            }
        }
        
        internal static string QRCODE_CONTENT_STRING {
            get {
                return ResourceManager.GetString("QRCODE_CONTENT_STRING", resourceCulture);
            }
        }
        
        internal static string INPUT_MAP_NAME_STRING {
            get {
                return ResourceManager.GetString("INPUT_MAP_NAME_STRING", resourceCulture);
            }
        }
        
        internal static string MAP_NAME_STRING {
            get {
                return ResourceManager.GetString("MAP_NAME_STRING", resourceCulture);
            }
        }
        
        internal static string BACK_STRING {
            get {
                return ResourceManager.GetString("BACK_STRING", resourceCulture);
            }
        }
        
        internal static string HOSPITAL_NAME_STRING {
            get {
                return ResourceManager.GetString("HOSPITAL_NAME_STRING", resourceCulture);
            }
        }
        
        internal static string TAIPEI_CITY_HALL_STRING {
            get {
                return ResourceManager.GetString("TAIPEI_CITY_HALL_STRING", resourceCulture);
            }
        }
        
        internal static string PICK_LOCATION_STRING {
            get {
                return ResourceManager.GetString("PICK_LOCATION_STRING", resourceCulture);
            }
        }
        
        internal static string CATEGORY_CLINICS_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_CLINICS_STRING", resourceCulture);
            }
        }
        
        internal static string CATEGORY_CASHIER_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_CASHIER_STRING", resourceCulture);
            }
        }
        
        internal static string CATEGORY_EXIT_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_EXIT_STRING", resourceCulture);
            }
        }
        
        internal static string CATEGORY_EXAMINATION_ROOM_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_EXAMINATION_ROOM_STRING", resourceCulture);
            }
        }
        
        internal static string CATEGORY_PHARMACY_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_PHARMACY_STRING", resourceCulture);
            }
        }
        
        internal static string CATEGORY_CONVENIENCE_STORE_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_CONVENIENCE_STORE_STRING", resourceCulture);
            }
        }
        
        internal static string CATEGORY_OTHERS_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_OTHERS_STRING", resourceCulture);
            }
        }
        
        internal static string CATEGORY_BATH_ROOM_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_BATH_ROOM_STRING", resourceCulture);
            }
        }
        
        internal static string CATEGORY_BLOOD_COLLECTION_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_BLOOD_COLLECTION_STRING", resourceCulture);
            }
        }
        
        internal static string CATEGORY_ELEVATOR_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_ELEVATOR_STRING", resourceCulture);
            }
        }
        
        internal static string CATEGORY_PARKING_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_PARKING_STRING", resourceCulture);
            }
        }
        
        internal static string CATEGORY_OFFICE_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_OFFICE_STRING", resourceCulture);
            }
        }
        
        internal static string CATEGORY_CONFERENCE_ROOM_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_CONFERENCE_ROOM_STRING", resourceCulture);
            }
        }
        
        internal static string CATEGORY_STAIR_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_STAIR_STRING", resourceCulture);
            }
        }
        
        internal static string PICK_DESTINATION_STRING {
            get {
                return ResourceManager.GetString("PICK_DESTINATION_STRING", resourceCulture);
            }
        }
        
        internal static string ROUTE_OPTION_STRING {
            get {
                return ResourceManager.GetString("ROUTE_OPTION_STRING", resourceCulture);
            }
        }
        
        internal static string AVOID_STAIR_STRING {
            get {
                return ResourceManager.GetString("AVOID_STAIR_STRING", resourceCulture);
            }
        }
        
        internal static string AVOID_ELEVATOR_STRING {
            get {
                return ResourceManager.GetString("AVOID_ELEVATOR_STRING", resourceCulture);
            }
        }
        
        internal static string AVOID_ESCALATOR_STRING {
            get {
                return ResourceManager.GetString("AVOID_ESCALATOR_STRING", resourceCulture);
            }
        }
        
        internal static string AVOID_ALL_CONNECTION_TYPE_STRING {
            get {
                return ResourceManager.GetString("AVOID_ALL_CONNECTION_TYPE_STRING", resourceCulture);
            }
        }
        
        internal static string DESTINATION_STRING {
            get {
                return ResourceManager.GetString("DESTINATION_STRING", resourceCulture);
            }
        }
        
        internal static string CURRENT_LOCATION_STRING {
            get {
                return ResourceManager.GetString("CURRENT_LOCATION_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_INITIAIL_FACE_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_INITIAIL_FACE_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_INITIAIL_BACK_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_INITIAIL_BACK_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_INITIAIL_CROSS_REGION_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_INITIAIL_CROSS_REGION_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_STRAIGHT_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_STRAIGHT_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_RIGHT_FRONT_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_RIGHT_FRONT_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_RIGHT_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_RIGHT_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_RIGHT_REAR_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_RIGHT_REAR_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_REAR_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_REAR_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_LEFT_REAR_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_LEFT_REAR_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_LEFT_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_LEFT_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_LEFT_FRONT_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_LEFT_FRONT_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_UP_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_UP_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_DOWN_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_DOWN_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_WRONG_WAY_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_WRONG_WAY_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_ARRIVED_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_ARRIVED_STRING", resourceCulture);
            }
        }
        
        internal static string NULL_STRING {
            get {
                return ResourceManager.GetString("NULL_STRING", resourceCulture);
            }
        }
        
        internal static string PICK_REGION_STRING {
            get {
                return ResourceManager.GetString("PICK_REGION_STRING", resourceCulture);
            }
        }
        
        internal static string FLOOR_STRING {
            get {
                return ResourceManager.GetString("FLOOR_STRING", resourceCulture);
            }
        }
        
        internal static string PLEASE_CHECK_INTERNET_STRING {
            get {
                return ResourceManager.GetString("PLEASE_CHECK_INTERNET_STRING", resourceCulture);
            }
        }
        
        internal static string PLEASE_ADJUST_AVOID_ROUTE_STRING {
            get {
                return ResourceManager.GetString("PLEASE_ADJUST_AVOID_ROUTE_STRING", resourceCulture);
            }
        }
        
        internal static string RSSI_OPTION_STRING {
            get {
                return ResourceManager.GetString("RSSI_OPTION_STRING", resourceCulture);
            }
        }
        
        internal static string STRONG_STRING {
            get {
                return ResourceManager.GetString("STRONG_STRING", resourceCulture);
            }
        }
        
        internal static string MEDIUM_STRING {
            get {
                return ResourceManager.GetString("MEDIUM_STRING", resourceCulture);
            }
        }
        
        internal static string WEAK_STRING {
            get {
                return ResourceManager.GetString("WEAK_STRING", resourceCulture);
            }
        }
        
        internal static string PLEASE_CONTROL_RSSI_OPTION_STRING {
            get {
                return ResourceManager.GetString("PLEASE_CONTROL_RSSI_OPTION_STRING", resourceCulture);
            }
        }
        
        internal static string GO_STRAIGHT_STRING {
            get {
                return ResourceManager.GetString("GO_STRAIGHT_STRING", resourceCulture);
            }
        }
        
        internal static string TURN_RIGHT_STRING {
            get {
                return ResourceManager.GetString("TURN_RIGHT_STRING", resourceCulture);
            }
        }
        
        internal static string TURN_LEFT_STRING {
            get {
                return ResourceManager.GetString("TURN_LEFT_STRING", resourceCulture);
            }
        }
        
        internal static string TURN_BACK_STRING {
            get {
                return ResourceManager.GetString("TURN_BACK_STRING", resourceCulture);
            }
        }
        
        internal static string TURN_RIGHT_FRONT_STRING {
            get {
                return ResourceManager.GetString("TURN_RIGHT_FRONT_STRING", resourceCulture);
            }
        }
        
        internal static string TURN_RIGHT_REAR_STRING {
            get {
                return ResourceManager.GetString("TURN_RIGHT_REAR_STRING", resourceCulture);
            }
        }
        
        internal static string TURN_LEFT_FRONT_STRING {
            get {
                return ResourceManager.GetString("TURN_LEFT_FRONT_STRING", resourceCulture);
            }
        }
        
        internal static string TURN_LEFT_REAR_STRING {
            get {
                return ResourceManager.GetString("TURN_LEFT_REAR_STRING", resourceCulture);
            }
        }
        
        internal static string LAB_STRING {
            get {
                return ResourceManager.GetString("LAB_STRING", resourceCulture);
            }
        }
        
        internal static string ELEVATOR_STRING {
            get {
                return ResourceManager.GetString("ELEVATOR_STRING", resourceCulture);
            }
        }
        
        internal static string STAIR_STRING {
            get {
                return ResourceManager.GetString("STAIR_STRING", resourceCulture);
            }
        }
        
        internal static string ESCALATOR_STRING {
            get {
                return ResourceManager.GetString("ESCALATOR_STRING", resourceCulture);
            }
        }
        
        internal static string NORMALHALLWAY_STRING {
            get {
                return ResourceManager.GetString("NORMALHALLWAY_STRING", resourceCulture);
            }
        }
        
        internal static string PICTURE_DIRECTION_STRING {
            get {
                return ResourceManager.GetString("PICTURE_DIRECTION_STRING", resourceCulture);
            }
        }
        
        internal static string NO_SIGNAL_STRING {
            get {
                return ResourceManager.GetString("NO_SIGNAL_STRING", resourceCulture);
            }
        }
    }
}
