//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoorNavigation.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_zh {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_zh() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("IndoorNavigation.Resources.AppResources.zh", typeof(AppResources_zh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        internal static string PickLocation {
            get {
                return ResourceManager.GetString("PickLocation", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        internal static string DownloadNavigraph {
            get {
                return ResourceManager.GetString("DownloadNavigraph", resourceCulture);
            }
        }
        
        internal static string DeleteNavigraph {
            get {
                return ResourceManager.GetString("DeleteNavigraph", resourceCulture);
            }
        }
        
        internal static string VoiceTest {
            get {
                return ResourceManager.GetString("VoiceTest", resourceCulture);
            }
        }
        
        internal static string PLAY_VOICE_TEST_STRING {
            get {
                return ResourceManager.GetString("PLAY_VOICE_TEST_STRING", resourceCulture);
            }
        }
        
        internal static string VOICE_SELECT_STRING {
            get {
                return ResourceManager.GetString("VOICE_SELECT_STRING", resourceCulture);
            }
        }
        
        internal static string VOICE_SETTING_STRING {
            get {
                return ResourceManager.GetString("VOICE_SETTING_STRING", resourceCulture);
            }
        }
        
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        internal static string LicenseAndPrivacy {
            get {
                return ResourceManager.GetString("LicenseAndPrivacy", resourceCulture);
            }
        }
        
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        internal static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        internal static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        internal static string AboutBeDI {
            get {
                return ResourceManager.GetString("AboutBeDI", resourceCulture);
            }
        }
        
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        internal static string VoiceSpeak {
            get {
                return ResourceManager.GetString("VoiceSpeak", resourceCulture);
            }
        }
        
        internal static string CultureVersion {
            get {
                return ResourceManager.GetString("CultureVersion", resourceCulture);
            }
        }
        
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string GotoNavigationHomePage {
            get {
                return ResourceManager.GetString("GotoNavigationHomePage", resourceCulture);
            }
        }
        
        internal static string Flash {
            get {
                return ResourceManager.GetString("Flash", resourceCulture);
            }
        }
        
        internal static string CHOOSE_MAP_STRING {
            get {
                return ResourceManager.GetString("CHOOSE_MAP_STRING", resourceCulture);
            }
        }
        
        internal static string ALL_STRING {
            get {
                return ResourceManager.GetString("ALL_STRING", resourceCulture);
            }
        }
        
        internal static string WARN_STRING {
            get {
                return ResourceManager.GetString("WARN_STRING", resourceCulture);
            }
        }
        
        internal static string ASK_IF_CANCEL_ALL_MAP_STRING {
            get {
                return ResourceManager.GetString("ASK_IF_CANCEL_ALL_MAP_STRING", resourceCulture);
            }
        }
        
        internal static string ASK_IF_CANCEL_MAP_STRING {
            get {
                return ResourceManager.GetString("ASK_IF_CANCEL_MAP_STRING", resourceCulture);
            }
        }
        
        internal static string MESSAGE_STRING {
            get {
                return ResourceManager.GetString("MESSAGE_STRING", resourceCulture);
            }
        }
        
        internal static string SUCCESSFULLY_DELETE_STRING {
            get {
                return ResourceManager.GetString("SUCCESSFULLY_DELETE_STRING", resourceCulture);
            }
        }
        
        internal static string MAP_STRING {
            get {
                return ResourceManager.GetString("MAP_STRING", resourceCulture);
            }
        }
        
        internal static string ERROR_STRING {
            get {
                return ResourceManager.GetString("ERROR_STRING", resourceCulture);
            }
        }
        
        internal static string ERROR_TO_DELETE_STRING {
            get {
                return ResourceManager.GetString("ERROR_TO_DELETE_STRING", resourceCulture);
            }
        }
        
        internal static string SUCCESSFULLY_DOWNLOAD_MAP_STRING {
            get {
                return ResourceManager.GetString("SUCCESSFULLY_DOWNLOAD_MAP_STRING", resourceCulture);
            }
        }
        
        internal static string FAILED_DOWNLOAD_MAP_STRING {
            get {
                return ResourceManager.GetString("FAILED_DOWNLOAD_MAP_STRING", resourceCulture);
            }
        }
        
        internal static string NOTIFY_STRING {
            get {
                return ResourceManager.GetString("NOTIFY_STRING", resourceCulture);
            }
        }
        
        internal static string SURE_TO_OPEN_WEBSITE_STRING {
            get {
                return ResourceManager.GetString("SURE_TO_OPEN_WEBSITE_STRING", resourceCulture);
            }
        }
        
        internal static string QRCODE_CONTENT_STRING {
            get {
                return ResourceManager.GetString("QRCODE_CONTENT_STRING", resourceCulture);
            }
        }
        
        internal static string INPUT_MAP_NAME_STRING {
            get {
                return ResourceManager.GetString("INPUT_MAP_NAME_STRING", resourceCulture);
            }
        }
        
        internal static string MAP_NAME_STRING {
            get {
                return ResourceManager.GetString("MAP_NAME_STRING", resourceCulture);
            }
        }
        
        internal static string BACK_STRING {
            get {
                return ResourceManager.GetString("BACK_STRING", resourceCulture);
            }
        }
        
        internal static string NTUH_YUNLIN_NAME_STRING {
            get {
                return ResourceManager.GetString("NTUH_YUNLIN_NAME_STRING", resourceCulture);
            }
        }
        
        internal static string PICK_LOCATION_STRING {
            get {
                return ResourceManager.GetString("PICK_LOCATION_STRING", resourceCulture);
            }
        }
        
        internal static string ROUTE_OPTION_STRING {
            get {
                return ResourceManager.GetString("ROUTE_OPTION_STRING", resourceCulture);
            }
        }
        
        internal static string AVOID_STAIR_STRING {
            get {
                return ResourceManager.GetString("AVOID_STAIR_STRING", resourceCulture);
            }
        }
        
        internal static string AVOID_ELEVATOR_STRING {
            get {
                return ResourceManager.GetString("AVOID_ELEVATOR_STRING", resourceCulture);
            }
        }
        
        internal static string AVOID_ESCALATOR_STRING {
            get {
                return ResourceManager.GetString("AVOID_ESCALATOR_STRING", resourceCulture);
            }
        }
        
        internal static string DESTINATION_STRING {
            get {
                return ResourceManager.GetString("DESTINATION_STRING", resourceCulture);
            }
        }
        
        internal static string CURRENT_LOCATION_STRING {
            get {
                return ResourceManager.GetString("CURRENT_LOCATION_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_STRAIGHT_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_STRAIGHT_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_RIGHT_FRONT_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_RIGHT_FRONT_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_RIGHT_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_RIGHT_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_RIGHT_REAR_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_RIGHT_REAR_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_REAR_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_REAR_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_LEFT_REAR_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_LEFT_REAR_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_LEFT_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_LEFT_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_LEFT_FRONT_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_LEFT_FRONT_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_UP_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_UP_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_DOWN_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_DOWN_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_WRONG_WAY_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_WRONG_WAY_STRING", resourceCulture);
            }
        }
        
        internal static string DIRECTION_ARRIVED_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_ARRIVED_STRING", resourceCulture);
            }
        }
        
        internal static string NULL_STRING {
            get {
                return ResourceManager.GetString("NULL_STRING", resourceCulture);
            }
        }
        
        internal static string PICK_DESTINATION_STRING {
            get {
                return ResourceManager.GetString("PICK_DESTINATION_STRING", resourceCulture);
            }
        }
        
        internal static string FLOOR_STRING {
            get {
                return ResourceManager.GetString("FLOOR_STRING", resourceCulture);
            }
        }
    }
}
